version: '3.8'

services:
# make this command on docker-compose: docker run -d --rm --hostname my-rabbitmq --name my-rabbitmq -e RABBITMQ_DEFAULT_USER=test-user -e RABBITMQ_DEFAULT_PASS=test-password -p 0.0.0.0:5672:5672 -p 0.0.0.0:15672:15672 rabbitmq:3-management
  rabbitmq:
    image: rabbitmq:3-management
    hostname: my-rabbitmq
    extra_hosts:       
      - "host.docker.internal:host-gateway"
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: test-user
      RABBITMQ_DEFAULT_PASS: test-password
    volumes:
      - ./components/rabbitmq/rabbitmq_data:/var/lib/rabbitmq

  jaeger:
    image: jaegertracing/all-in-one:1.46
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=:9411
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16685:16685
      - 16686:16686
      - 14268:14268
      - 14269:14269
      - 14250:14250
      # - 9411:9411
      - 4317:4317
      - 4318:4318

  prometheus:
      extra_hosts:       
      - "host.docker.internal:host-gateway"
      image: prom/prometheus:v2.36.2
      volumes:
        - ./components/prometheus:/etc/prometheus/
        - ./observability/prometheus_data:/prometheus
      command:
        - '--config.file=/etc/prometheus/prometheus.yml'
        - '--storage.tsdb.path=/prometheus'
        - '--web.console.libraries=/usr/share/prometheus/console_libraries'
        - '--web.console.templates=/usr/share/prometheus/consoles'
      ports:
        - 9090:9090
      # links:
  #      - pushgateway:pushgateway
      # networks:
        # - back-tier
      restart: always

  grafana:
    image: grafana/grafana:latest
    ports:
      - '3001:300'
    volumes:
      - ./observability/grafana-data:/var/lib/grafana
    depends_on:
      - loki
    extra_hosts:       
    - "host.docker.internal:host-gateway"
    restart: unless-stopped

  loki:
    image: grafana/loki:latest
    ports:
      - '3100:3100'
    volumes:
      - ./observability/loki-data:/data
    extra_hosts:       
    - "host.docker.internal:host-gateway"
    # networks:
    #   - monitoring

# networks:
#   monitoring:

# volumes:
#   grafana-data: 
#   loki-data:

