GET http://localhost:3000/register?name=🦁

###

GET  http://localhost:3000/register?name=🐺

###

GET http://localhost:3000/register?name=🐱

###

GET http://localhost:3000/register?name=🐭

###

GET http://localhost:3000/register?name=🐹

###

GET http://localhost:3000/register?name=🐰

###

GET http://localhost:3000/register?name=🦊

###

GET http://localhost:3000/register?name=🐻

###

GET http://localhost:3000/register?name=🐼

###

GET http://localhost:3000/register?name=🐨

###

GET http://localhost:3000/register?name=🐯

###

GET http://localhost:3000/register?name=🐥